---
name: Tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9.0-rc - 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Ensure latest setuptools
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          python -m pip install coverage tox tox-factor unittest-xml-reporting
      - name: Run tox
        run: |
          python -m pip --version
          python -m tox --version
          python -m tox -f py$(python --version 2>&1 | cut -c 8,10)
      - name: Coverage reporting
        run: |
          coverage combine
          coverage report -m
          coverage xml
          coverage html
      - name: Publish coverage results
        uses: codecov/codecov-action@v1


  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Ensure latest setuptools
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          python -m pip install tox
      - name: Run tox
        run: |
          python -m pip --version
          python -m tox --version
          python -m tox -e isort,lint,docs


  warnings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Ensure latest setuptools
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Install dependencies
        run: |
          python -m pip install tox
      - name: Run tox
        run: |
          python -m pip --version
          python -m tox --version
          python -m tox -e warnings
